export const crew = [
  {
    slug: 'samuel-mercer',
    name: 'Samuel Mercer',
    callsign: 'Mercer',
    role: 'Command',
    status: 'Active',
    origin: 'Erevos City, Mars',
    specialty: 'Command under pressure • anomaly triage',
    portrait: '/crew/Sam.png',
    sceneThumb: '/scenes/bridge-incident.jpg',
    tags: ['POV', 'Captain', 'GECO'],
  },
  {
    slug: 'raj-malik',
    name: 'Raj Malik',
    callsign: 'Raj',
    role: 'Pilot',
    status: 'Active',
    origin: 'New Delhi, Earth',
    specialty: 'Manual piloting • thermal crisis response',
    portrait: '/crew/Raj.png',
    sceneThumb: '/scenes/blue-star-heat.jpg',
    tags: ['Pilot', 'Dry humor'],
  },
  {
    slug: 'lexie-howard',
    name: 'Lexie Howard',
    callsign: 'Lexie',
    role: 'Navigation',
    status: 'Active',
    origin: 'Bristol, UK',
    specialty: 'Course corrections • deep-field mapping',
    portrait: '/crew/Lexie.png',
    sceneThumb: '/scenes/obsidian-corridor.jpg',
    tags: ['Navigation', 'British'],
  },
  {
    slug: 'sofia-reyes',
    name: 'Sofia Reyes',
    callsign: 'Sofia',
    role: 'Engineering',
    status: 'Active',
    origin: 'Monterrey, Mexico',
    specialty: 'Jump systems • improvised repairs',
    portrait: '/crew/Sofia.png',
    sceneThumb: '/scenes/engine-bay.jpg',
    tags: ['Engineer', 'Sharp tongue'],
  },
  {
    slug: 'timothy-everett',
    name: 'Timothy N. Everett',
    callsign: 'Tiny',
    role: 'Science',
    status: 'Active',
    origin: 'Callisto',
    specialty: 'Signal analysis • anomaly linguistics',
    portrait: '/crew/Tiny.png',
    sceneThumb: '/scenes/prime-numbers.jpg',
    tags: ['Science', 'Quiet'],
  },
  {
    slug: 'sadie',
    name: 'SADIE',
    role: 'AI',
    status: 'Classified',
    origin: 'Onboard core',
    specialty: 'Neural interface • survival constraints',
    portrait: '/crew/SADIE.png',
    sceneThumb: '/scenes/hud-overlay.jpg',
    tags: ['AI', 'Symbiosis'],
  },
]
